version: "3"
services:
  server:
    build:
      context: ./src
    ports:
      - 5202:8080
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_ENVIRONMENT: Development
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      ConnectionStrings__DbContext: Host=db:5432;Username=admin;Password=admin;Database=postgres
    restart: on-failure
    profiles:
      - complete
  migrate:
    build:
      context: ./src
    entrypoint: sh
    command: -c './DbMigrationsBundle --connection "$${MIGRATION_CONNECTION}"'
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      MIGRATION_CONNECTION: Host=db:5432;Username=admin;Password=admin;Database=postgres
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
      interval: 10s
      retries: 10
      start_period: 10s
    restart: unless-stopped
volumes:
  postgres: ~
